sudo: required
services:
  -docker

before_install:
  - docker build -t pradeepkala/docker-react -f Dockerfile.dev .

script:
  - docker run pradeepkala/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app:  "docker-react"
  env:  "DockerReact-env"
  bucket_name:  "elasticbeanstalk-ap-south-1-329927167428"
  bucket_path:  "docker-react"
  on:
    branch: master
  access_key_id:  
    secure: $aws-access-key
  secret_access_key:
    secure: "$aws-secret-key"

    
